advert:
    resource: "@AdvertBundle/Resources/config/routing.yml"
    prefix:   /advert

asset:
    resource: "@AssetBundle/Resources/config/routing.yml"
    prefix:   /
#asset
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

