parameters:
    my_user_provider.class: Master\UserBundle\Security\Core\User\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments: [@fos_user.user_manager.default,{facebook: facebook_id}]